var dest={
  "anywhere": "",
  "africa": "region/1uw0",
  "asia": "region/2CIv",
  "central america":"region/2Bcw,region/22wS",
  "europe": "region/26m5",
  "oceania":"region/25Cs",
  "south america":"region/20oH",
  "north america":"region/21TO",
  "african": "region/1uw0",
  "asian": "region/2CIv",
  "central american":"region/2Bcw,region/22wS",
  "european": "region/26m5",
  "oceanian":"region/25Cs",
  "south american":"region/20oH",
  "north american":"region/21TO",
  "outside us": "region/20oH,region/26m5,region/2CIv,region/25Cs,region/1uw0,country/2BFn,region/2FyS",
  "aarhus": "airport/AAR",
  "abadan": "airport/ABD",
  "abeche": "airport/AEH",
  "aberdeen": "airport/ABZ",
  "abidjan": "airport/ABJ",
  "abilene": "airport/ABI",
  "abu dhabi": "airport/AUH",
  "abu rudeis": "airport/AUE",
  "abu simbel": "airport/ABS",
  "abuja": "airport/ABV",
  "acapulco": "airport/ACA",
  "accra": "airport/ACC",
  "adana": "airport/ADA",
  "addis ababa": "airport/ADD",
  "adelaide": "airport/ADL",
  "aden": "airport/ADE",
  "adiyaman": "airport/ADF",
  "adler/sochi": "airport/AER",
  "agades": "airport/AJY",
  "agadir": "airport/AGA",
  "agana": "airport/SUM",
  "aggeneys": "airport/AGZ",
  "aguadilla": "airport/BQN",
  "aguascaliente": "airport/AGU",
  "ahmedabad": "airport/AMD",
  "aiyura": "airport/AYU",
  "ajaccio": "airport/AJA",
  "akita": "airport/AXT",
  "akron": "airport/CAK",
  "akrotiri": "airport/AKT",
  "al ain": "airport/AAN",
  "al arish": "airport/AAC",
  "al hoceima": "airport/AHU",
  "albany": "airport/ALH",
  "albany": "airport/ALB",
  "albi": "airport/LBI",
  "alborg": "airport/AAL",
  "albuquerque": "airport/ABQ",
  "albury": "airport/ABX",
  "alderney": "airport/ACI",
  "aleppo": "airport/ALP",
  "alesund": "airport/AES",
  "alexander bay": "airport/ALJ",
  "alexandria": "airport/ESF",
  "alexandria": "airport/ALY",
  "alfujairah": "airport/FJR",
  "alghero sassari": "airport/AHO",
  "algiers": "airport/ALG",
  "alicante": "airport/ALC",
  "alice springs": "airport/ASP",
  "alldays": "airport/ADY",
  "allentown": "airport/ABE",
  "almaty": "airport/ALA",
  "almeria": "airport/LEI",
  "alta": "airport/ALF",
  "altay": "airport/AAT",
  "altenrhein": "airport/ACH",
  "altoona": "airport/AOO",
  "altus": "airport/AXS",
  "amami": "airport/ASJ",
  "amarillo": "airport/AMA",
  "amazon bay": "airport/AZB",
  "amman": "airport/AMM",
  "amritsar": "airport/ATQ",
  "amsterdam": "airport/AMS",
  "anand": "airport/QNB",
  "anchorage": "airport/ANC",
  "ancona": "airport/AOI",
  "andorra la vella": "airport/ALV",
  "anguilla": "airport/AXA",
  "anjouan": "airport/AJN",
  "ankara": "airport/ANK",
  "ankara": "airport/ESB",
  "ann arbor": "airport/ARB",
  "annaba": "airport/AAE",
  "annecy": "airport/NCY",
  "anniston": "airport/ANB",
  "antalya": "airport/AYT",
  "antananarivo": "airport/TNR",
  "antigua": "airport/ANU",
  "antwerp": "airport/ANR",
  "aomori": "airport/AOJ",
  "apia": "airport/APW",
  "appelton/neenah/menasha": "airport/ATW",
  "aqaba": "airport/AQJ",
  "aracaju": "airport/AJU",
  "araxos": "airport/GPA",
  "arkhangelsk": "airport/ARH",
  "arlit": "airport/RLT",
  "arrecife/lanzarote": "airport/ACE",
  "aruba": "airport/AUA",
  "arusha": "airport/ARK",
  "asheville": "airport/AVL",
  "ashgabat": "airport/ASB",
  "asmara": "airport/ASM",
  "aspen": "airport/ASE",
  "assiut": "airport/ATZ",
  "astana": "airport/TSE",
  "asuncion": "airport/ASU",
  "aswan": "airport/ASW",
  "athens": "airport/HEW",
  "athens": "airport/ATH",
  "atlanta": "airport/ATL",
  "atlantic city": "airport/ACY",
  "attawapiskat": "airport/YAT",
  "auckland": "airport/AKL",
  "augsburg": "airport/AGB",
  "augusta": "airport/AGS",
  "augusta": "airport/AUG",
  "aurillac": "airport/AUR",
  "austin": "airport/AUS",
  "ayawasi": "airport/AYW",
  "ayers rock": "airport/AYQ",
  "ayr": "airport/AYR",
  "badajoz": "airport/BJZ",
  "bagdad": "airport/BGW",
  "bagdogra": "airport/IXB",
  "bahamas": "airport/NAS",
  "bahawalpur": "airport/BHV",
  "bahrain": "airport/BAH",
  "bakersfield": "airport/BFL",
  "baku": "airport/BAK",
  "ballina": "airport/BNK",
  "baltimore": "airport/BWI",
  "bamaga": "airport/ABM",
  "bamako": "airport/BKO",
  "bambari": "airport/BBY",
  "bandar seri begawan": "airport/BWN",
  "bandung": "airport/BDO",
  "bangalore": "airport/BLR",
  "bangassou": "airport/BGU",
  "bangkok": "airport/BKK",
  "bangor": "airport/BGR",
  "bangui": "airport/BGF",
  "banjul": "airport/BJL",
  "bannu": "airport/BNP",
  "barcelona": "airport/BCN",
  "bardufoss": "airport/BDU",
  "bari": "airport/BRI",
  "barisal": "airport/BZL",
  "baroda": "airport/BDQ",
  "barra": "airport/BRR",
  "barranquilla": "airport/BAQ",
  "basel": "airport/BSL",
  "basel/mulhouse": "airport/EAP",
  "basra": "airport/BSR",
  "basse": "airport/PTP",
  "basseterre": "airport/SKB",
  "bastia": "airport/BIA",
  "baton rouge": "airport/BTR",
  "bayreuth": "airport/BYU",
  "beaumont/pt. arthur": "airport/BPT",
  "beckley": "airport/BKW",
  "beef island": "airport/EIS",
  "beijing": "airport/PEK",
  "beijing": "airport/NAY",
  "beira": "airport/BEW",
  "beirut": "airport/BEY",
  "belem": "airport/BEL",
  "belfast": "airport/BFS",
  "belgaum": "airport/IXG",
  "belgrad": "airport/BEG",
  "belize city": "airport/BZE",
  "bellingham": "airport/BLI",
  "belo horizonte": "airport/CNF",
  "bemidji": "airport/BJI",
  "benbecula": "airport/BEB",
  "benghazi": "airport/BEN",
  "benguela": "airport/BUG",
  "benton harbour": "airport/BEH",
  "berberati": "airport/BBT",
  "bergamo/milan": "airport/BGY",
  "bergen": "airport/BGO",
  "bergerac": "airport/EGC",
  "berlin": "airport/BER",
  "bermuda": "airport/BDA",
  "berne": "airport/BRN",
  "bethel": "airport/BET",
  "bhopal": "airport/BHO",
  "bhubaneswar": "airport/BBI",
  "biarritz": "airport/BIQ",
  "bilbao": "airport/BIO",
  "billings": "airport/BIL",
  "billund": "airport/BLL",
  "bintulu": "airport/BTU",
  "biraro": "airport/IRO",
  "birmingham": "airport/BHM",
  "birmingham": "airport/BHX",
  "bishkek": "airport/FRU",
  "bismarck": "airport/BIS",
  "bissau": "airport/BXO",
  "blackpool": "airport/BLK",
  "blackwater": "airport/BLT",
  "blantyre": "airport/BLZ",
  "blenheim": "airport/BHE",
  "bloemfontein": "airport/BFN",
  "bloomington": "airport/BMG",
  "bluefield": "airport/BLF",
  "boa vista": "airport/BVB",
  "bobo/dioulasso": "airport/BOY",
  "bodo": "airport/BOO",
  "bodrum": "airport/BJV",
  "bogota": "airport/BOG",
  "boise": "airport/BOI",
  "bologna": "airport/BLQ",
  "bombay": "airport/BOM",
  "bonaire": "airport/BON",
  "bonaventure": "airport/YVB",
  "bora bora": "airport/BOB",
  "bordeaux": "airport/BOD",
  "borrego springs": "airport/BXS",
  "boston": "airport/BOS",
  "bouake": "airport/BYK",
  "bourgas/burgas": "airport/BOJ",
  "bournemouth": "airport/BOH",
  "bowen": "airport/ZBO",
  "bozeman": "airport/BZN",
  "bradford/warren": "airport/BFD",
  "brainerd": "airport/BRD",
  "brampton island": "airport/BMP",
  "brasilia": "airport/BSB",
  "bratislava": "airport/BTS",
  "brazzaville": "airport/BZV",
  "bremen": "airport/BRE",
  "brescia": "airport/VBS",
  "brest": "airport/BES",
  "bria": "airport/BIV",
  "bridgeport": "airport/BDR",
  "bridgetown": "airport/BGI",
  "brindisi": "airport/BDS",
  "brisbane": "airport/BNE",
  "bristol": "airport/BRS",
  "broennoeysund": "airport/BNN",
  "broken hill": "airport/BHQ",
  "brookings": "airport/BKX",
  "broome": "airport/BME",
  "brunswick": "airport/BQK",
  "brussels": "airport/BRU",
  "bucaramanga": "airport/BGA",
  "bucharest": "airport/BUH",
  "bucharest": "airport/OTP",
  "budapest": "airport/BUD",
  "buenos aires": "airport/BUE",
  "buffalo range": "airport/BFO",
  "buffalo/niagara falls": "airport/BUF",
  "bujumbura": "airport/BJM",
  "bulawayo": "airport/BUQ",
  "bullhead city": "airport/BHC",
  "bundaberg": "airport/BDB",
  "burbank": "airport/BUR",
  "burlington": "airport/BTV",
  "burlington ia": "airport/BRL",
  "burnie": "airport/BWT",
  "butte": "airport/BTM",
  "cabinda": "airport/CAB",
  "cagliari": "airport/CAG",
  "cairns": "airport/CNS",
  "cairo": "airport/CAI",
  "calama": "airport/CJC",
  "calcutta": "airport/CCU",
  "calgary": "airport/YYC",
  "cali": "airport/CLO",
  "calicut": "airport/CCJ",
  "calvi": "airport/CLY",
  "cambridge bay": "airport/YCB",
  "cambrigde": "airport/CBG",
  "campbeltown": "airport/CAL",
  "campo grande": "airport/CGR",
  "canberra": "airport/CBR",
  "cancun": "airport/CUN",
  "canouan": "airport/CIW",
  "cape town": "airport/CPT",
  "caracas": "airport/CCS",
  "cardiff": "airport/CWL",
  "carlsbad": "airport/CLD",
  "carnarvon": "airport/CVQ",
  "carnot": "airport/CRF",
  "carson city": "airport/CSN",
  "cartagena": "airport/CTG",
  "casablanca": "airport/CAS",
  "casino": "airport/CSI",
  "casper": "airport/CPR",
  "castaway": "airport/CST",
  "castries": "airport/SLU",
  "catania": "airport/CTA",
  "cayenne": "airport/CAY",
  "cebu city": "airport/CEB",
  "cedar city": "airport/CDC",
  "cedar rapids ia": "airport/CID",
  "ceduna": "airport/CED",
  "cessnock": "airport/CES",
  "chabarovsk": "airport/KHV",
  "chambery": "airport/CMF",
  "champaign": "airport/CMI",
  "chandigarh": "airport/IXC",
  "changchun": "airport/CGQ",
  "chania": "airport/CHQ",
  "chaoyang": "airport/CHG",
  "charleston": "airport/CHS",
  "charleston": "airport/CRW",
  "charlotte": "airport/CLT",
  "charlottesville": "airport/CHO",
  "charters towers": "airport/CXT",
  "chattanooga": "airport/CHA",
  "chengdu": "airport/CTU",
  "chennai": "airport/MAA",
  "cheyenne": "airport/CYS",
  "chiang mai": "airport/CNX",
  "chiba city": "airport/QCB",
  "chicago": "airport/ORD",
  "chichen itza": "airport/CZA",
  "chico": "airport/CIC",
  "chihuahua": "airport/CUU",
  "chios": "airport/JKH",
  "chipata": "airport/CIP",
  "chisinau": "airport/KIV",
  "chita": "airport/HTA",
  "chitral": "airport/CJL",
  "chittagong": "airport/CGP",
  "chongqing": "airport/CKG",
  "christchurch": "airport/CHC",
  "chub cay": "airport/CCZ",
  "churchill": "airport/YYQ",
  "cienfuegos": "airport/CFG",
  "cincinnati": "airport/CVG",
  "ciudad del carmen": "airport/CME",
  "ciudad guayana": "airport/CGU",
  "ciudad juarez": "airport/CJS",
  "ciudad obregon": "airport/CEN",
  "ciudad victoria": "airport/CVM",
  "clarksburg": "airport/CKB",
  "clermont": "airport/CMQ",
  "clermont ferrand": "airport/CFE",
  "cleveland": "airport/CLE",
  "cochabamba": "airport/CBB",
  "cochin": "airport/COK",
  "cody/powell/yellowstone": "airport/COD",
  "coffmann cove": "airport/KCC",
  "coffs harbour": "airport/CFS",
  "coimbatore": "airport/CJB",
  "colima": "airport/CLQ",
  "college station/bryan": "airport/CLL",
  "collinsville": "airport/KCE",
  "cologne": "airport/CGN",
  "colombo": "airport/CMB",
  "colorado springs": "airport/COS",
  "columbia": "airport/CAE",
  "columbus": "airport/CSG",
  "columbus": "airport/CMH",
  "conakry": "airport/CKY",
  "concord": "airport/CCR",
  "concord": "airport/CON",
  "constanta": "airport/CND",
  "constantine": "airport/CZL",
  "coober pedy": "airport/CPD",
  "cooktown": "airport/CTN",
  "cooma": "airport/OOM",
  "copenhagen": "airport/CPH",
  "cordoba": "airport/ODB",
  "corfu": "airport/CFU",
  "cork": "airport/ORK",
  "corpus christi": "airport/CRP",
  "cotonou": "airport/COO",
  "cottbus": "airport/CBU",
  "coventry": "airport/CVT",
  "cozmel": "airport/CZM",
  "craig": "airport/CGA",
  "crescent city": "airport/CEC",
  "cuiaba": "airport/CGB",
  "culiacan": "airport/CUL",
  "curacao": "airport/CUR",
  "curitiba": "airport/CWB",
  "cuyo": "airport/CYU",
  "dakar": "airport/DKR",
  "dalaman": "airport/DLM",
  "dalby": "airport/DBY",
  "dalian": "airport/DLC",
  "dallas": "airport/DAL",
  "dallas/ft. worth": "airport/DFW",
  "daloa": "airport/DJO",
  "damascus": "airport/DAM",
  "dammam": "airport/DMM",
  "danville": "airport/DAN",
  "dar es salam": "airport/DAR",
  "darwin": "airport/DRW",
  "daydream island": "airport/DDI",
  "dayton": "airport/DAY",
  "daytona beach": "airport/DAB",
  "decatur": "airport/DEC",
  "deer lake/corner brook": "airport/YDF",
  "delhi": "airport/DEL",
  "den haag": "airport/HAG",
  "denizli": "airport/DNZ",
  "denpasar/bali": "airport/DPS",
  "denver": "airport/DEN",
  "dera ismail khan": "airport/DSK",
  "derby": "airport/DRB",
  "derry": "airport/LDY",
  "des moines": "airport/DSM",
  "detroit": "airport/DET",
  "devils lake": "airport/DVL",
  "devonport": "airport/DPO",
  "dhahran": "airport/DHA",
  "dhaka": "airport/DAC",
  "dili": "airport/DIL",
  "dillingham": "airport/DLG",
  "dinard": "airport/DNR",
  "disneyland paris": "airport/DLP",
  "djerba": "airport/DJE",
  "djibouti": "airport/JIB",
  "dodoma": "airport/DOD",
  "doha": "airport/DOH",
  "doncaster/sheffield": "airport/DSA",
  "donegal": "airport/CFN",
  "dortmund": "airport/DTM",
  "dothan": "airport/DHN",
  "douala": "airport/DLA",
  "dresden": "airport/DRS",
  "dubai": "airport/DXB",
  "dubbo": "airport/DBO",
  "dublin": "airport/DUB",
  "dubois": "airport/DUJ",
  "dubrovnik": "airport/DBV",
  "dubuque ia": "airport/DBQ",
  "duesseldorf": "airport/DUS",
  "duluth": "airport/DLH",
  "dundee": "airport/DND",
  "dunedin": "airport/DUD",
  "dunk island": "airport/DKI",
  "durango": "airport/DRO",
  "durban": "airport/DUR",
  "dushanbe": "airport/DYU",
  "dutch harbor": "airport/DUT",
  "dysart": "airport/DYA",
  "dzaoudzi": "airport/DZA",
  "east london": "airport/ELS",
  "easter island": "airport/IPC",
  "eau clarie": "airport/EAU",
  "edinburgh": "airport/EDI",
  "edmonton": "airport/YEA",
  "egilsstadir": "airport/EGS",
  "eindhoven": "airport/EIN",
  "el minya": "airport/EMY",
  "el paso": "airport/ELP",
  "elat": "airport/ETH",
  "elba island": "airport/EBA",
  "elkhart": "airport/EKI",
  "elko": "airport/EKO",
  "ellisras": "airport/ELL",
  "elmira": "airport/ELM",
  "ely": "airport/ELY",
  "emerald": "airport/EMD",
  "enontekioe": "airport/ENF",
  "entebbe": "airport/EBB",
  "erfurt": "airport/ERF",
  "erie": "airport/ERI",
  "eriwan": "airport/EVN",
  "erzincan": "airport/ERC",
  "erzurum": "airport/ERZ",
  "esbjerg": "airport/EBJ",
  "escanaba": "airport/ESC",
  "esperance": "airport/EPR",
  "eugene": "airport/EUG",
  "eureka": "airport/ACV",
  "evansville": "airport/EVV",
  "evenes": "airport/EVE",
  "exeter": "airport/EXT",
  "fair isle": "airport/FIE",
  "fairbanks": "airport/FAI",
  "faisalabad": "airport/LYP",
  "fargo": "airport/FAR",
  "farmington": "airport/FMN",
  "faro": "airport/FAO",
  "faroer": "airport/FAE",
  "fayetteville": "airport/FYV",
  "fayetteville/ft. bragg": "airport/FAY",
  "fes": "airport/FEZ",
  "figari": "airport/FSC",
  "flagstaff": "airport/FLG",
  "flin flon": "airport/YFO",
  "flint": "airport/FNT",
  "florence": "airport/FLO",
  "florence": "airport/FLR",
  "florianopolis": "airport/FLN",
  "floro": "airport/FRO",
  "fort albert": "airport/YFA",
  "fort de france": "airport/FDF",
  "fort dodge ia": "airport/FOD",
  "fort huachuca/sierra vista": "airport/FHU",
  "fort lauderdale/hollywood": "airport/FLL",
  "fort mcmurray": "airport/YMM",
  "fort myers": "airport/FMY",
  "fort riley": "airport/FRI",
  "fort smith": "airport/YSM",
  "fort st. john": "airport/YXJ",
  "fort walton beach": "airport/VPS",
  "fort wayne": "airport/FWA",
  "fort worth": "airport/DFW",
  "fortaleza": "airport/FOR",
  "foula": "airport/FOU",
  "francistown": "airport/FRW",
  "frankfurt/hahn": "airport/HHN",
  "frankfurt/main": "airport/FRA",
  "franklin/oil city": "airport/FKL",
  "fredericton": "airport/YFC",
  "freeport": "airport/FPO",
  "freetown": "airport/FNA",
  "frejus": "airport/FRJ",
  "fresno": "airport/FAT",
  "friedrichshafen": "airport/FDH",
  "fuerteventura": "airport/FUE",
  "fujairah": "airport/FJR",
  "fukuoka": "airport/FUK",
  "fukushima": "airport/FKS",
  "funchal": "airport/FNC",
  "futuna": "airport/FUT",
  "gaborone": "airport/GBE",
  "gadsden": "airport/GAD",
  "gainesville": "airport/GNV",
  "galway": "airport/GWY",
  "gander": "airport/YQX",
  "garoua": "airport/GOU",
  "gaza city": "airport/GZA",
  "gaziantep": "airport/GZT",
  "gdansk": "airport/GDN",
  "geelong": "airport/GEX",
  "geneva": "airport/GVA",
  "genoa": "airport/GOA",
  "george": "airport/GRJ",
  "georgetown": "airport/GEO",
  "geraldton": "airport/GET",
  "gerona": "airport/GRO",
  "ghent": "airport/GNE",
  "gibraltar": "airport/GIB",
  "gilette": "airport/GCC",
  "gilgit": "airport/GIL",
  "gillam": "airport/YGX",
  "gladstone": "airport/GLT",
  "glasgow": "airport/GLA",
  "glendive": "airport/GDV",
  "goa": "airport/GOI",
  "goiania": "airport/GYN",
  "gold coast": "airport/OOL",
  "goondiwindi": "airport/GOO",
  "goose bay": "airport/YYR",
  "gorna": "airport/GOZ",
  "gothenburg": "airport/GOT",
  "gove": "airport/GOV",
  "govenors harbour": "airport/GHB",
  "granada": "airport/GRX",
  "grand bahamainternational": "airport/FPO",
  "grand canyon": "airport/GCN",
  "grand cayman": "airport/GCM",
  "grand forks": "airport/GFK",
  "grand junction": "airport/GJT",
  "grand rapids": "airport/GRR",
  "graz": "airport/GRZ",
  "great falls": "airport/GTF",
  "great keppel island": "airport/GKL",
  "green bay": "airport/GRB",
  "greenbrier/lewisburg": "airport/LWB",
  "greensboro/winston salem": "airport/GSO",
  "greenville": "airport/PGV",
  "greenville/spartanburg": "airport/GSP",
  "grenada": "airport/GND",
  "grenoble": "airport/GNB",
  "griffith": "airport/GFF",
  "groningen": "airport/GRQ",
  "groote eylandt": "airport/GTE",
  "groton/new london": "airport/GON",
  "guadalajara": "airport/GDL",
  "guadalcanal": "airport/GSI",
  "guam": "airport/GUM",
  "guangzhou": "airport/CAN",
  "guatemala city": "airport/GUA",
  "guayaquil": "airport/GYE",
  "guernsey": "airport/GCI",
  "guettin": "airport/GTI",
  "guilin": "airport/KWL",
  "gulfport/biloxi": "airport/GPT",
  "gulu": "airport/ULU",
  "gunnison/crested butte": "airport/GUC",
  "guwahati": "airport/GAU",
  "gwadar": "airport/GWD",
  "gweru": "airport/GWE",
  "gympie": "airport/GYP",
  "hachijo jima": "airport/HAC",
  "hagåtña": "airport/GUM",
  "haifa": "airport/HFA",
  "haines": "airport/HNS",
  "hakodate": "airport/HKD",
  "halifax international": "airport/YHZ",
  "hall beach": "airport/YUX",
  "hamburg": "airport/HAM",
  "hamilton": "airport/YHM",
  "hamilton island": "airport/HTI",
  "hammerfest": "airport/HFT",
  "hancock": "airport/CMX",
  "hangchow": "airport/HGH",
  "hannover": "airport/HAJ",
  "hanoi": "airport/HAN",
  "harare": "airport/HRE",
  "harbin": "airport/HRB",
  "harlingen/south padre island": "airport/HRL",
  "harrington harbour": "airport/YHR",
  "harrisburg": "airport/MDT",
  "hartford": "airport/BDL",
  "hatyai": "airport/HDY",
  "haugesund": "airport/HAU",
  "havana": "airport/HAV",
  "havre": "airport/HVR",
  "hayman island": "airport/HIS",
  "helena": "airport/HLN",
  "helsingborg": "airport/JHE",
  "helsinki": "airport/HEL",
  "heraklion": "airport/HER",
  "hermosillo": "airport/HMO",
  "hervey bay": "airport/HVB",
  "hibbing": "airport/HIB",
  "hickory": "airport/HKY",
  "hilo": "airport/ITO",
  "hilton head island": "airport/HHH",
  "hinchinbrook island": "airport/HNK",
  "hiroshima international": "airport/HIJ",
  "ho chi minh city": "airport/SGN",
  "hobart": "airport/HBA",
  "hof": "airport/HOQ",
  "holguin": "airport/HOG",
  "home hill": "airport/HMH",
  "homer": "airport/HOM",
  "hong kong": "airport/HKG",
  "honiarahenderson international": "airport/HIR",
  "honolulu": "airport/HNL",
  "hoonah": "airport/HNH",
  "horta": "airport/HOR",
  "houston": "airport/IAH",
  "houston": "airport/HOU",
  "huahine": "airport/HUH",
  "huatulco": "airport/HUX",
  "hue": "airport/HUI",
  "humberside": "airport/HUY",
  "huntington": "airport/HTS",
  "huntsville": "airport/HSV",
  "hurghada international": "airport/HRG",
  "huron": "airport/HON",
  "hwange national park": "airport/HWN",
  "hyannis": "airport/HYA",
  "hydaburg": "airport/HYG",
  "hyderabad": "airport/HYD",
  "ibiza": "airport/IBZ",
  "idaho falls": "airport/IDA",
  "iguazu": "airport/IGR",
  "ile des pins": "airport/ILP",
  "ile ouen": "airport/IOU",
  "iliamna": "airport/ILI",
  "imperial": "airport/IPL",
  "incercargill": "airport/IVC",
  "incheon": "airport/ICN",
  "indianapolis": "airport/IND",
  "ingham": "airport/IGH",
  "innisfail": "airport/IFL",
  "innsbruck": "airport/INN",
  "international falls": "airport/INL",
  "inuvik": "airport/YEV",
  "invercargill": "airport/IVC",
  "inverness": "airport/INV",
  "inykern": "airport/IYK",
  "iqaluit": "airport/YFB",
  "iquitos": "airport/IQT",
  "irkutsk": "airport/IKT",
  "ishigaki": "airport/ISG",
  "islamabad": "airport/ISB",
  "islay": "airport/ILY",
  "isle of man": "airport/IOM",
  "istanbul": "airport/IST",
  "ithaca/cortland": "airport/ITH",
  "ivalo": "airport/IVL",
  "ixtapa/zihuatenejo": "airport/ZIH",
  "izmir": "airport/IZM",
  "jackson": "airport/JAN",
  "jacksonville": "airport/JAX",
  "jacmel ": "airport/JAK",
  "jacobabad": "airport/JAG",
  "jacobina ": "airport/JCM",
  "jacquinot bay": "airport/JAQ",
  "jaffna": "airport/JAF",
  "jagdalpur": "airport/JGB",
  "jaipur": "airport/JAI",
  "jaisalmer ": "airport/JSA",
  "jakarta": "airport/CGK",
  "jalalabad  ": "airport/JAA",
  "jalandhar": "airport/JLR",
  "jalapa": "airport/JAL",
  "jales": "airport/JLS",
  "jaluit island ": "airport/UIT",
  "jamba": "airport/JMB",
  "jambi": "airport/DJB",
  "jambol": "airport/JAM",
  "jammu": "airport/IXJ",
  "jamnagar": "airport/JGA",
  "jamshedpur": "airport/IXW",
  "janakpur": "airport/JKR",
  "jandakot": "airport/JAD",
  "janesville": "airport/JVL",
  "januaria": "airport/JNA",
  "jaque ": "airport/JQE",
  "jatai": "airport/JTI",
  "jauja": "airport/JAU",
  "jayapura": "airport/DJJ",
  "jeddah": "airport/JED",
  "jefferson city": "airport/JEF",
  "jeremie": "airport/JEE",
  "jerez de la frontera/cadiz": "airport/XRY",
  "jersey": "airport/JER",
  "jerusalem": "airport/JRS",
  "jessore": "airport/JSR",
  "jeypore": "airport/PYB",
  "jiamusi": "airport/JMU",
  "ji'an": "airport/JGS",
  "jiayuguan": "airport/JGN",
  "jijel": "airport/GJL",
  "jijiga": "airport/JIJ",
  "jilin": "airport/JIL",
  "jimma": "airport/JIM",
  "jinan": "airport/TNA",
  "jingdezhen": "airport/JDZ",
  "jinghong": "airport/JHG",
  "jining": "airport/JNG",
  "jinja": "airport/JIN",
  "jinjiang": "airport/JJN",
  "jinka": "airport/BCO",
  "jinzhou": "airport/JNZ",
  "jipijapa": "airport/JIP",
  "jiri": "airport/JIR",
  "jiujiang": "airport/JIU",
  "jiwani": "airport/JIW",
  "joacaba": "airport/JCB",
  "joao pessoa": "airport/JPA",
  "jodhpur": "airport/JDH",
  "joensuu": "airport/JOE",
  "johannesburg": "airport/JNB",
  "johnson city": "airport/BGM",
  "johnston island": "airport/JON",
  "johnstown": "airport/JST",
  "johor bahru": "airport/JHB",
  "joinville": "airport/JOI",
  "jolo": "airport/JOL",
  "jomsom": "airport/JMO",
  "jonesboro": "airport/JBR",
  "jönköping": "airport/JKG",
  "joplin": "airport/JLN",
  "jorhat": "airport/JRH",
  "jos": "airport/JOS",
  "jose de san martin": "airport/JSM",
  "jouf": "airport/AJF",
  "juanjui": "airport/JJI",
  "juba": "airport/JUB",
  "juist": "airport/JUI",
  "juiz de fora": "airport/JDF",
  "jujuy": "airport/JUJ",
  "julia creek": "airport/JCK",
  "juliaca": "airport/JUL",
  "jumla": "airport/JUM",
  "jundah": "airport/JUN",
  "juneau": "airport/JNU",
  "junin": "airport/JNI",
  "juticalpa": "airport/JUT",
  "jwaneng": "airport/JWA",
  "jyväskylä": "airport/JYV",
  "kabul": "airport/KBL",
  "kagoshima": "airport/KOJ",
  "kahramanmaras": "airport/KCM",
  "kahului": "airport/OGG",
  "kajaani": "airport/KAJ",
  "kalamata": "airport/KLX",
  "kalamazoo/battle creek": "airport/AZO",
  "kalgoorlie": "airport/KGI",
  "kalispell": "airport/FCA",
  "kalmar": "airport/KLR",
  "kamloops": "airport/YKA",
  "kamuela": "airport/MUE",
  "kano": "airport/KAN",
  "kanpur": "airport/KNU",
  "kansas city": "airport/MCI",
  "kaohsiung international": "airport/KHH",
  "kapalua west": "airport/JHM",
  "karachi": "airport/KHI",
  "karlsruhe": "airport/FKB",
  "karlstad": "airport/KSD",
  "karpathos": "airport/AOK",
  "karratha": "airport/KTA",
  "kars": "airport/KYS",
  "karumba": "airport/KRB",
  "karup": "airport/KRP",
  "kaschechawan": "airport/ZKE",
  "kassala": "airport/KSL",
  "katherine": "airport/KTR",
  "kathmandu": "airport/KTM",
  "katima mulilo/mpacha": "airport/MPA",
  "kauhajoki": "airport/KHJ",
  "kaunakakai": "airport/MKK",
  "kavalla": "airport/KVA",
  "kayseri": "airport/ASR",
  "kazan": "airport/KZN",
  "keetmanshoop": "airport/KMP",
  "kelowna": "airport/YLW",
  "kemi/tornio": "airport/KEM",
  "kenai": "airport/ENA",
  "kent": "airport/MSE",
  "kerry county": "airport/KIR",
  "ketchikan": "airport/KTN",
  "key west": "airport/EYW",
  "khamis mushayat": "airport/AHB",
  "kharga": "airport/UVL",
  "kharkov": "airport/HRK",
  "khartoum": "airport/KRT",
  "khuzdar": "airport/KDD",
  "kiel": "airport/KEL",
  "kiev": "airport/KBP",
  "kigali": "airport/KGL",
  "kilimadjaro": "airport/JRO",
  "killeem": "airport/ILE",
  "kimberley": "airport/KIM",
  "king island": "airport/KNS",
  "king salomon": "airport/AKN",
  "kingscote": "airport/KGC",
  "kingston": "airport/ISO",
  "kingston": "airport/KIN",
  "kingstown": "airport/SVD",
  "kinshasa": "airport/FIH",
  "kiritimati": "airport/CXI",
  "kirkenes": "airport/KKN",
  "kirkuk": "airport/KIK",
  "kirkwall": "airport/KOI",
  "kiruna": "airport/KRN",
  "kisangani": "airport/FKI",
  "kittilä": "airport/KTT",
  "kitwe": "airport/KIW",
  "klagenfurt": "airport/KLU",
  "klamath fall": "airport/LMT",
  "klawock": "airport/KLW",
  "kleinsee": "airport/KLZ",
  "knock": "airport/NOC",
  "knoxville": "airport/TYS",
  "kobe": "airport/UKB",
  "kochi": "airport/KCZ",
  "kodiak": "airport/ADQ",
  "kohat": "airport/OHT",
  "kokkola/pietarsaari": "airport/KOK",
  "kolkata": "airport/CCU",
  "köln": "airport/CGN",
  "komatsu": "airport/KMQ",
  "kona": "airport/KOA",
  "konya": "airport/KYA",
  "korhogo": "airport/HGO",
  "kos": "airport/KGS",
  "kota kinabalu": "airport/BKI",
  "kotzbue": "airport/OTZ",
  "kowanyama": "airport/KWM",
  "krakow": "airport/KRK",
  "kristiansand": "airport/KRS",
  "kristianstad": "airport/KID",
  "kristiansund": "airport/KSU",
  "kuala lumpur": "airport/KUL",
  "kuantan": "airport/KUA",
  "kuching": "airport/KCH",
  "kumamoto": "airport/KMJ",
  "kununurra": "airport/KNX",
  "kuopio": "airport/KUO",
  "kushiro": "airport/KUH",
  "kuujjuaq": "airport/YVP",
  "kuujjuarapik": "airport/YGW",
  "kuusamo": "airport/KAO",
  "kuwait": "airport/KWI",
  "kyoto": "airport/UKY",
  "la coruna": "airport/LCG",
  "la crosse": "airport/LSE",
  "la grande": "airport/YGL",
  "la paz": "airport/LAP",
  "la paz": "airport/LPB",
  "la rochelle": "airport/LRH",
  "la romana": "airport/LRM",
  "labe": "airport/LEK",
  "labouchere bay": "airport/WLB",
  "labuan": "airport/LBU",
  "lac brochet": "airport/XLB",
  "lae": "airport/LAE",
  "lafayette": "airport/LAF",
  "lagos": "airport/LOS",
  "lahore": "airport/LHE",
  "lake charles": "airport/LCH",
  "lake havasu city": "airport/HII",
  "lake tahoe": "airport/TVL",
  "lakselv": "airport/LKL",
  "lambarene": "airport/LBQ",
  "lamezia terme": "airport/SUF",
  "lampedusa": "airport/LMP",
  "lanai city": "airport/LNY",
  "lancaster": "airport/LNS",
  "land's end": "airport/LEQ",
  "langkawi": "airport/LGK",
  "lannion": "airport/LAI",
  "lanseria": "airport/HLA",
  "lansing": "airport/LAN",
  "lappeenranta": "airport/LPP",
  "laramie": "airport/LAR",
  "laredo": "airport/LRD",
  "larnaca": "airport/LCA",
  "las palmas": "airport/LPA",
  "las vegas": "airport/LAS",
  "latrobe": "airport/LBE",
  "launceston": "airport/LST",
  "laurel/hattisburg": "airport/PIB",
  "laverton": "airport/LVO",
  "lawton": "airport/LAW",
  "lazaro cardenas": "airport/LZC",
  "leaf rapids": "airport/YLR",
  "learmouth": "airport/LEA",
  "lebanon": "airport/LEB",
  "leeds/bradford": "airport/LBA",
  "leinster": "airport/LER",
  "leipzig": "airport/LEJ",
  "lelystad": "airport/LEY",
  "leon": "airport/BJX",
  "leonora": "airport/LNO",
  "lerwick/tingwall": "airport/LWK",
  "lewiston": "airport/LWS",
  "lewistown": "airport/LWT",
  "lexington": "airport/LEX",
  "libreville": "airport/LBV",
  "lidkoeping": "airport/LDK",
  "liege": "airport/LGG",
  "lifou": "airport/LIF",
  "lihue": "airport/LIH",
  "lille": "airport/LIL",
  "lilongwe": "airport/LLW",
  "lima": "airport/LIM",
  "limassol": "airport/QLI",
  "limoges": "airport/LIG",
  "lincoln": "airport/LNK",
  "lindeman island": "airport/LDC",
  "linz": "airport/LNZ",
  "lisala": "airport/LIQ",
  "lisbon": "airport/LIS",
  "lismore": "airport/LSY",
  "little rock": "airport/LIT",
  "liverpool": "airport/LPL",
  "lizard island": "airport/LZR",
  "ljubljana": "airport/LJU",
  "lockhart river": "airport/IRG",
  "lome": "airport/LFW",
  "london": "airport/LON",
  "londonderry": "airport/LDY",
  "long beach": "airport/LGB",
  "long island": "airport/LIJ",
  "longreach": "airport/LRE",
  "longview/kilgore": "airport/GGG",
  "longyearbyen": "airport/LYR",
  "loreto": "airport/LTO",
  "lorient": "airport/LRT",
  "los angeles": "airport/LAX",
  "los cabos": "airport/SJD",
  "los mochis": "airport/LMM",
  "los rodeos": "airport/TFN",
  "losinj": "airport/LSZ",
  "louisville": "airport/SDF",
  "lourdes/tarbes": "airport/LDE",
  "luanda": "airport/LAD",
  "lubbock": "airport/LBB",
  "lucknow": "airport/LKO",
  "luederitz": "airport/LUD",
  "luga": "airport/MLA",
  "lugano": "airport/LUG",
  "lulea": "airport/LLA",
  "lumbumbashi": "airport/FBM",
  "lusaka": "airport/LUN",
  "lusisiki": "airport/LUJ",
  "luxembourg": "airport/LUX",
  "luxi": "airport/LUM",
  "luxor": "airport/LXR",
  "lvov": "airport/LWO",
  "lydd": "airport/LYX",
  "lynchburg": "airport/LYH",
  "lyon": "airport/LYN",
  "lyons": "airport/LYO",
  "maastricht/aachen": "airport/MST",
  "macapa": "airport/MCP",
  "macau": "airport/MFM",
  "maceio": "airport/MCZ",
  "mackay": "airport/MKY",
  "macon": "airport/MCN",
  "mactan island": "airport/NOP",
  "madinah": "airport/MED",
  "madison": "airport/MSN",
  "madras": "airport/MAA",
  "madrid": "airport/MAD",
  "mahe": "airport/SEZ",
  "mahon": "airport/MAH",
  "maitland": "airport/MTL",
  "majunga": "airport/MJN",
  "makung": "airport/MZG",
  "malabo": "airport/SSG",
  "malaga": "airport/AGP",
  "malatya": "airport/MLX",
  "male": "airport/MLE",
  "malindi": "airport/MYD",
  "malmo": "airport/MMX",
  "man": "airport/MJC",
  "manado": "airport/MDC",
  "managua": "airport/MGA",
  "manaus": "airport/MAO",
  "manchester": "airport/MAN",
  "mandalay": "airport/MDL",
  "manguna": "airport/MFO",
  "manihi": "airport/XMH",
  "manila": "airport/MNL",
  "manzanillo": "airport/ZLO",
  "manzini": "airport/MTS",
  "maputo": "airport/MPM",
  "mar del plata": "airport/MDQ",
  "maracaibo": "airport/MAR",
  "maradi": "airport/MFQ",
  "maras": "airport/KCM",
  "marathon": "airport/MTH",
  "mardin": "airport/MQM",
  "mare": "airport/MEE",
  "margate": "airport/MGH",
  "margerita": "airport/PMV",
  "maribor": "airport/MBX",
  "mariehamn": "airport/MHQ",
  "maroua": "airport/MVR",
  "marquette": "airport/MQT",
  "marrakesh": "airport/RAK",
  "marsa alam": "airport/RMF",
  "marsa matrah": "airport/MUH",
  "marseille": "airport/MRS",
  "marsh harbour": "airport/MHH",
  "martha's vineyard": "airport/MVY",
  "martinsburg": "airport/MRB",
  "maryborough": "airport/MBH",
  "maseru": "airport/MSU",
  "mason city ia": "airport/MCW",
  "masvingo": "airport/MVZ",
  "matsumoto": "airport/MMJ",
  "matsuyama": "airport/MYJ",
  "mattoon": "airport/MTO",
  "maun": "airport/MUB",
  "maupiti": "airport/MAU",
  "mauritius": "airport/MRU",
  "mayaguez": "airport/MAZ",
  "mazatlan": "airport/MZT",
  "mcallen": "airport/MFE",
  "medan": "airport/KNO",
  "medellin": "airport/MDE",
  "medford": "airport/MFR",
  "medina": "airport/MED",
  "meekatharra": "airport/MKR",
  "melbourne": "airport/MLB",
  "melbourne": "airport/MEL",
  "melville hall": "airport/DOM",
  "memphis": "airport/MEM",
  "mendoza": "airport/MDZ",
  "merced": "airport/MCE",
  "merida": "airport/MID",
  "meridian": "airport/MEI",
  "merimbula": "airport/MIM",
  "messina": "airport/MEZ",
  "metlakatla": "airport/MTM",
  "metz": "airport/MZM",
  "metz/nancy metz": "airport/ETZ",
  "mexicali": "airport/MXL",
  "mexico city": "airport/MEX",
  "mfuwe": "airport/MFU",
  "miami": "airport/MIA",
  "mianwali": "airport/MWD",
  "middlemount": "airport/MMM",
  "midland/odessa": "airport/MAF",
  "midway island": "airport/MDY",
  "mikkeli": "airport/MIK",
  "milan": "airport/MIL",
  "mildura": "airport/MQL",
  "miles city": "airport/MLS",
  "milford sound": "airport/MFN",
  "milwaukee": "airport/MKE",
  "minatitlan": "airport/MTT",
  "mineralnye vody": "airport/MRV",
  "minneapolis": "airport/MSP",
  "minot": "airport/MOT",
  "minsk": "airport/MSQ",
  "miri": "airport/MYY",
  "mirpur": "airport/QML",
  "missula": "airport/MSO",
  "mitchell": "airport/MHE",
  "miyako jima": "airport/MMY",
  "miyazaki": "airport/KMI",
  "mkambati": "airport/MBM",
  "moanda": "airport/MFF",
  "mobile": "airport/MOB",
  "modesto": "airport/MOD",
  "moenjodaro": "airport/MJD",
  "mogadishu": "airport/MGQ",
  "mokuti": "airport/OKU",
  "moline/quad cities": "airport/MLI",
  "mombasa": "airport/MBA",
  "monastir": "airport/MIR",
  "moncton": "airport/YQM",
  "monroe": "airport/MLU",
  "monrovia": "airport/MLW",
  "montego bay": "airport/MBJ",
  "montenegro": "airport/QGF",
  "monterrey": "airport/MTY",
  "montevideo": "airport/MVD",
  "montgomery": "airport/MGM",
  "montpellier": "airport/MPL",
  "montreal": "airport/YUL",
  "montrose/tellruide": "airport/MTJ",
  "moorea": "airport/MOZ",
  "moranbah": "airport/MOV",
  "moree": "airport/MRZ",
  "morelia": "airport/MLM",
  "morgantown": "airport/MGW",
  "morioka": "airport/HNA",
  "moroni": "airport/HAH",
  "moruya": "airport/MYA",
  "moscow": "airport/MOW",
  "moses lake": "airport/MWH",
  "mossel bay": "airport/MZY",
  "mostar": "airport/OMO",
  "mosul": "airport/OSM",
  "mouila": "airport/MJL",
  "moundou": "airport/MQQ",
  "mount cook": "airport/GTN",
  "mount gambier": "airport/MGB",
  "mount magnet": "airport/MMG",
  "mt. isa": "airport/ISA",
  "mt. mckinley": "airport/MCL",
  "muenchen": "airport/MUC",
  "muenster/osnabrueck": "airport/FMO",
  "mulhouse": "airport/MLH",
  "multan": "airport/MUX",
  "murcia": "airport/MJV",
  "murmansk": "airport/MMK",
  "mus": "airport/MSR",
  "muscat": "airport/MCT",
  "muscle shoals": "airport/MSL",
  "muskegon": "airport/MKG",
  "muzaffarabad": "airport/MFG",
  "mvengue": "airport/MVB",
  "mykonos": "airport/JMK",
  "myrtle beach": "airport/CRE",
  "mysore": "airport/MYQ",
  "mytilene": "airport/MJT",
  "mzamba": "airport/MZF",
  "nadi": "airport/NAN",
  "nagasaki": "airport/NGS",
  "nagoya": "airport/NGO",
  "nagpur": "airport/NAG",
  "nairobi": "airport/NBO",
  "nakhichevan": "airport/NAJ",
  "nakhon si thammarat": "airport/NST",
  "nancy": "airport/ENC",
  "nanisivik": "airport/YSR",
  "nanning": "airport/NNG",
  "nantes": "airport/NTE",
  "nantucket": "airport/ACK",
  "naples": "airport/NAP",
  "narrabri": "airport/NAA",
  "narrandera": "airport/NRA",
  "narsarsuaq": "airport/UAK",
  "nashville": "airport/BNA",
  "nassau": "airport/NAS",
  "natal": "airport/NAT",
  "nausori": "airport/SUV",
  "nawab shah": "airport/WNS",
  "naxos": "airport/JNX",
  "n'djamena": "airport/NDJ",
  "n'dola": "airport/NLA",
  "nelson": "airport/NSN",
  "nelspruit": "airport/NLP",
  "nelspruit": "airport/MQP",
  "nevis": "airport/NEV",
  "new bern": "airport/EWN",
  "new haven": "airport/HVN",
  "new orleans": "airport/MSY",
  "new valley": "airport/UVL",
  "new york": "airport/LGA",
  "newburgh": "airport/SWF",
  "newcastle": "airport/NCL",
  "newman": "airport/ZNE",
  "newport news/williamsburg": "airport/PHF",
  "newquay": "airport/NQY",
  "n'gaoundere": "airport/NGE",
  "niagara falls international": "airport/IAG",
  "niamey": "airport/NIM",
  "nice": "airport/NCE",
  "nicosia": "airport/NIC",
  "niigata": "airport/KIJ",
  "nikolaev": "airport/NLV",
  "nimes": "airport/FNI",
  "nis": "airport/INI",
  "nome": "airport/OME",
  "noosa": "airport/NSA",
  "norfolk island": "airport/NLK",
  "norfolk/virginia beach": "airport/ORF",
  "norman wells": "airport/YVQ",
  "norrkoeping": "airport/NRK",
  "north bend": "airport/OTH",
  "north eleuthera": "airport/ELH",
  "norwich": "airport/NWI",
  "nottingham": "airport/EMA",
  "nouadhibou": "airport/NDB",
  "nouakchott": "airport/NKC",
  "noumea": "airport/NOU",
  "novi sad": "airport/QND",
  "novosibirsk": "airport/OVB",
  "nuevo laredo": "airport/NLD",
  "nuku'alofa": "airport/TBU",
  "nürnberg": "airport/NUE",
  "oakland": "airport/OAK",
  "oaxaca": "airport/OAX",
  "odense": "airport/ODE",
  "odessa": "airport/ODS",
  "oerebro": "airport/ORB",
  "ohrid": "airport/OHD",
  "oita": "airport/OIT",
  "okayama": "airport/OKJ",
  "okinawa": "airport/OKA",
  "oklahoma city": "airport/OKC",
  "olbia": "airport/OLB",
  "olympic dam": "airport/OLP",
  "omaha": "airport/OMA",
  "ondangwa": "airport/OND",
  "ontario": "airport/ONT",
  "oran": "airport/ORN",
  "orange": "airport/OAG",
  "orange county": "airport/SNA",
  "oranjemund": "airport/OMD",
  "oranjestad": "airport/AUA",
  "orkney": "airport/KOI",
  "orlando": "airport/MCO",
  "orlandometropolitan area": "airport/ORL",
  "orpheus island": "airport/ORS",
  "osaka": "airport/OSA",
  "oshkosh": "airport/OSH",
  "osijek": "airport/OSI",
  "oslo": "airport/OSL",
  "ottawa": "airport/YOW",
  "ouadda": "airport/ODA",
  "ouagadougou": "airport/OUA",
  "ouarzazate": "airport/OZZ",
  "oudtshoorn": "airport/OUH",
  "oujda": "airport/OUD",
  "oulu": "airport/OUL",
  "out skerries": "airport/OUK",
  "oviedo": "airport/OVD",
  "owensboro": "airport/OWB",
  "oxnard": "airport/OXR",
  "oyem": "airport/UVE",
  "paderborn/lippstadt": "airport/PAD",
  "paducah": "airport/PAH",
  "page/lake powell": "airport/PGA",
  "pago pago": "airport/PPG",
  "pakersburg": "airport/PKB",
  "palermo": "airport/PMO",
  "palm springs": "airport/PSP",
  "palma de mallorca": "airport/PMI",
  "palmas": "airport/PMW",
  "palmdale/lancaster": "airport/PMD",
  "palmerston north": "airport/PMR",
  "panama city": "airport/PFN",
  "panama city": "airport/PTY",
  "panjgur": "airport/PJG",
  "pantelleria": "airport/PNL",
  "papeete": "airport/PPT",
  "paphos": "airport/PFO",
  "paraburdoo": "airport/PBO",
  "paramaribo": "airport/PBM",
  "paris": "airport/PAR",
  "paro": "airport/PBH",
  "pasco": "airport/PSC",
  "pasni": "airport/PSI",
  "patna": "airport/PAT",
  "pattaya": "airport/PYX",
  "pau": "airport/PUF",
  "pellston": "airport/PLN",
  "penang international": "airport/PEN",
  "pendelton": "airport/PDT",
  "pensacola": "airport/PNS",
  "peoria/bloomington": "airport/PIA",
  "pereira": "airport/PEI",
  "perpignan": "airport/PGF",
  "perthinternational": "airport/PER",
  "perugia": "airport/PEG",
  "pescara": "airport/PSR",
  "peshawar": "airport/PEW",
  "petersburg": "airport/PSG",
  "phalaborwa": "airport/PHW",
  "philadelphia": "airport/PHL",
  "phnom penh": "airport/PNH",
  "phoenix": "airport/PHX",
  "phuket": "airport/HKT",
  "pierre": "airport/PIR",
  "pietermaritzburg": "airport/PZB",
  "pietersburg": "airport/PTG",
  "pilanesberg/sun city": "airport/NTY",
  "pisa": "airport/PSA",
  "pittsburghinternational airport": "airport/PIT",
  "plattsburgh": "airport/PLB",
  "plettenberg bay": "airport/PBZ",
  "pocatello": "airport/PIH",
  "podgorica": "airport/TGD",
  "pohnpei": "airport/PNI",
  "pointe a pitre": "airport/PTP",
  "pointe noire": "airport/PNR",
  "poitiers": "airport/PIS",
  "ponce": "airport/PSE",
  "ponta delgada": "airport/PDL",
  "pori": "airport/POR",
  "port angeles": "airport/CLM",
  "port au prince": "airport/PAP",
  "port augusta": "airport/PUG",
  "port elizabeth": "airport/PLZ",
  "port gentil": "airport/POG",
  "port harcourt": "airport/PHC",
  "port hedland": "airport/PHE",
  "port lincoln": "airport/PLO",
  "port macquarie": "airport/PQQ",
  "port menier": "airport/YPN",
  "port moresby": "airport/POM",
  "port of spain": "airport/POS",
  "port said": "airport/PSD",
  "port vila": "airport/VLI",
  "portland": "airport/PTJ",
  "portlandinternational": "airport/PDX",
  "porto": "airport/OPO",
  "porto alegre": "airport/POA",
  "porto santo": "airport/PXO",
  "porto velho": "airport/PVH",
  "poughkeepsie": "airport/POU",
  "poznan": "airport/POZ",
  "prague": "airport/PRG",
  "praia": "airport/RAI",
  "presque island": "airport/PQI",
  "pretoria": "airport/PRY",
  "preveza/lefkas": "airport/PVK",
  "prince george": "airport/YXS",
  "prince rupert/digby island": "airport/YPR",
  "pristina": "airport/PRN",
  "prosperpine": "airport/PPP",
  "providence": "airport/PVD",
  "prudhoe bay": "airport/SCC",
  "pu san": "airport/PUS",
  "puebla": "airport/PBC",
  "pueblo": "airport/PUB",
  "puerto escondido": "airport/PXM",
  "puerto ordaz": "airport/PZO",
  "puerto plata": "airport/POP",
  "puerto vallarta": "airport/PVR",
  "pukatawagan": "airport/XPK",
  "pula": "airport/PUY",
  "pullman": "airport/PUW",
  "pune": "airport/PNQ",
  "punta arenas": "airport/PUQ",
  "punta cana": "airport/PUJ",
  "pyongyang": "airport/FNJ",
  "qingdao": "airport/TAO",
  "quebec": "airport/YQB",
  "queenstown": "airport/UEE",
  "quetta": "airport/UET",
  "quimper": "airport/UIP",
  "quincy": "airport/UIN",
  "quito": "airport/UIO",
  "rabat": "airport/RBA",
  "rahim yar khan": "airport/RYK",
  "raiatea": "airport/RFP",
  "rainbow lake": "airport/YOP",
  "rajkot": "airport/RAJ",
  "raleigh/durham": "airport/RDU",
  "ranchi": "airport/IXR",
  "rangiroa": "airport/RGI",
  "rangoon": "airport/RGN",
  "rapid city": "airport/RAP",
  "rarotonga": "airport/RAR",
  "ras al khaymah": "airport/RKT",
  "rawala kot": "airport/RAZ",
  "rawalpindi": "airport/RWP",
  "reading": "airport/RDG",
  "recife": "airport/REC",
  "redding": "airport/RDD",
  "redmond": "airport/RDM",
  "reggio calabria": "airport/REG",
  "regina": "airport/YQR",
  "reina sofia": "airport/TFS",
  "rennes": "airport/RNS",
  "reno": "airport/RNO",
  "resolute bay": "airport/YRB",
  "reus": "airport/REU",
  "reykjavik": "airport/REK",
  "rhinelander": "airport/RHI",
  "rhodos": "airport/RHO",
  "richards bay": "airport/RCB",
  "richmond": "airport/RIC",
  "riga": "airport/RIX",
  "rijeka": "airport/RJK",
  "rimini": "airport/RMI",
  "rio branco": "airport/RBR",
  "rio de janeiro": "airport/RIO",
  "riyadh": "airport/RUH",
  "roanne": "airport/RNE",
  "roanoke": "airport/ROA",
  "roatan": "airport/RTB",
  "rochester": "airport/ROC",
  "rock sound": "airport/RSD",
  "rock springs": "airport/RKS",
  "rockford": "airport/RFD",
  "rockhampton": "airport/ROK",
  "rockland": "airport/RKD",
  "rocky mount": "airport/RWI",
  "rodez": "airport/RDZ",
  "rodrigues island": "airport/RRG",
  "roenne": "airport/RNN",
  "rome": "airport/ROM",
  "ronneby": "airport/RNB",
  "rosario": "airport/ROS",
  "rotorua": "airport/ROT",
  "rotterdam": "airport/RTM",
  "rovaniemi": "airport/RVN",
  "rundu": "airport/NDU",
  "ruse": "airport/ROU",
  "saarbruecken": "airport/SCN",
  "sacramento": "airport/SMF",
  "sado shima": "airport/SDS",
  "saginaw/bay city/midland": "airport/MBS",
  "saidu sharif": "airport/SDT",
  "saigon": "airport/SGN",
  "saint brieuc": "airport/SBK",
  "saint denis de la reunion": "airport/RUN",
  "saint john": "airport/YSJ",
  "saipan": "airport/SPN",
  "sal": "airport/SID",
  "salalah": "airport/SLL",
  "salem": "airport/SLE",
  "salinas": "airport/SNC",
  "salisbury": "airport/SAY",
  "saloniki": "airport/SKG",
  "salt lake city": "airport/SLC",
  "salta": "airport/SLA",
  "salvador": "airport/SSA",
  "salzburg": "airport/SZG",
  "samana": "airport/AZS",
  "samarkand": "airport/SKD",
  "samos": "airport/SMI",
  "samsun": "airport/SZF",
  "san andres": "airport/ADZ",
  "san angelo": "airport/SJT",
  "san antonio": "airport/SAT",
  "san carlos de bariloche": "airport/BRC",
  "san diego": "airport/SAN",
  "san francisco": "airport/SFO",
  "san jose": "airport/SJO",
  "san jose cabo": "airport/SJD",
  "san jose": "airport/SJC",
  "san juan": "airport/SJU",
  "san luis obisco": "airport/SBP",
  "san luis potosi": "airport/SLP",
  "san pedro": "airport/SPY",
  "san pedro sula": "airport/SAP",
  "san salvador": "airport/SAL",
  "san sebastian": "airport/EAS",
  "sanaa": "airport/SAH",
  "sandspit": "airport/YZP",
  "santa ana": "airport/SNA",
  "santa barbara": "airport/SBA",
  "santa cruz de la palma": "airport/SPC",
  "santa cruz de la sierra": "airport/SRZ",
  "santa katarina": "airport/SKV",
  "santa maria": "airport/SMA",
  "santander": "airport/SDR",
  "santiago": "airport/SCU",
  "santiago de chile": "airport/SCL",
  "santiago de compostela": "airport/SCQ",
  "santo": "airport/SON",
  "santo domingo": "airport/SDQ",
  "sao luis": "airport/SLZ",
  "sao paulo": "airport/SAO",
  "sao tome": "airport/TMS",
  "sapporo": "airport/CTS",
  "sarajevo": "airport/SJJ",
  "sarasota/bradenton": "airport/SRQ",
  "saskatoon": "airport/YXE",
  "sassandra": "airport/ZSS",
  "savannah": "airport/SAV",
  "savonlinna": "airport/SVL",
  "scarborough": "airport/TAB",
  "scone": "airport/NSO",
  "scottsdale": "airport/SCF",
  "seattle/tacoma": "airport/SEA",
  "sehba": "airport/SEB",
  "seinaejoki": "airport/SJY",
  "selibi phikwe": "airport/PKW",
  "sendai": "airport/SDJ",
  "seoul": "airport/ICN",
  "sevilla": "airport/SVQ",
  "sfax": "airport/SFA",
  "shamattawa": "airport/ZTM",
  "shanghai": "airport/PVG",
  "shannon": "airport/SNN",
  "sharjah": "airport/SHJ",
  "sharm el sheikh": "airport/SSH",
  "sheffield": "airport/DSA",
  "shenandoah valley/stauton": "airport/SHD",
  "shenyang": "airport/SHE",
  "shenzhen": "airport/SZX",
  "sheridan": "airport/SHR",
  "shreveport": "airport/SHV",
  "shute harbour": "airport/JHQ",
  "sibu": "airport/SBW",
  "sidney": "airport/SDY",
  "silistra": "airport/SLS",
  "simferopol": "airport/SIP",
  "sindhri": "airport/MPD",
  "singapore": "airport/SIN",
  "singleton": "airport/SIX",
  "sioux city ia": "airport/SUX",
  "sioux falls": "airport/FSD",
  "sishen": "airport/SIS",
  "sitka": "airport/SIT",
  "sivas": "airport/VAS",
  "siwa": "airport/SEW",
  "skagway": "airport/SGY",
  "skardu": "airport/KDU",
  "skiathos": "airport/JSI",
  "skopje": "airport/SKP",
  "skrydstrup": "airport/SKS",
  "skukuza": "airport/SZK",
  "sligo": "airport/SXL",
  "smithers": "airport/YYD",
  "sodankylae": "airport/SOT",
  "soenderborg": "airport/SGD",
  "soendre stroemfjord": "airport/SFJ",
  "sofia": "airport/SOF",
  "sogndal": "airport/SOG",
  "south bend": "airport/SBN",
  "south indian lake": "airport/XSI",
  "south molle island": "airport/SOI",
  "southampton": "airport/SOU",
  "southend": "airport/SEN",
  "split": "airport/SPU",
  "spokane": "airport/GEG",
  "springbok": "airport/SBU",
  "springfield": "airport/SGF",
  "springfield": "airport/SPI",
  "srinagar": "airport/SXR",
  "st. augustin": "airport/YIF",
  "st. croix": "airport/STX",
  "st. etienne": "airport/EBU",
  "st. george": "airport/SGU",
  "st. john's": "airport/YYT",
  "st. kitts": "airport/SKB",
  "st. louis": "airport/STL",
  "st. lucia hewanorra": "airport/UVF",
  "st. lucia vigle": "airport/SLU",
  "st. marteen": "airport/SXM",
  "st. martin": "airport/SFG",
  "st. petersburg": "airport/LED",
  "st. pierre": "airport/FSP",
  "st. thomas": "airport/STT",
  "st. vincent": "airport/SVD",
  "stansted": "airport/STN",
  "state college/belefonte": "airport/SCE",
  "stavanger": "airport/SVG",
  "steamboat springs": "airport/HDN",
  "stettin": "airport/SZZ",
  "stockholm": "airport/ARN",
  "stockholmmetropolitan area": "airport/STO",
  "stockton": "airport/SCK",
  "stornway": "airport/SYY",
  "strassburg": "airport/SXB",
  "streaky bay": "airport/KBY",
  "stuttgart": "airport/STR",
  "sui": "airport/SUL",
  "sukkur": "airport/SKZ",
  "sumburgh": "airport/LSI",
  "sun valley": "airport/SUN",
  "sundsvall": "airport/SDL",
  "sunshine coast": "airport/MCY",
  "surabaya": "airport/SUB",
  "surat": "airport/STV",
  "suva/nausori": "airport/SUV",
  "swakopmund": "airport/SWP",
  "sydney": "airport/SYD",
  "sylhet": "airport/ZYL",
  "syracuse": "airport/SYR",
  "tabuk": "airport/TUU",
  "taif": "airport/TIF",
  "taipei": "airport/TPE",
  "taiyuan": "airport/TYN",
  "takamatsu": "airport/TAK",
  "talkeetna": "airport/TKA",
  "tallahassee": "airport/TLH",
  "tallinn": "airport/QUF",
  "tampa": "airport/TPA",
  "tampere": "airport/TMP",
  "tampico": "airport/TAM",
  "tamworth": "airport/TMW",
  "tangier": "airport/TNG",
  "taree": "airport/TRO",
  "targovishte": "airport/TGV",
  "tashkent": "airport/TAS",
  "tawau": "airport/TWU",
  "tbilisi": "airport/TBS",
  "te anau": "airport/TEU",
  "teesside": "airport/MME",
  "tegucigalpa": "airport/TGU",
  "tehran": "airport/THR",
  "tekirdag": "airport/TEQ",
  "tel aviv": "airport/TLV",
  "telluride": "airport/TEX",
  "temora": "airport/TEM",
  "tenerife": "airport/TCI",
  "tennant creek": "airport/TCA",
  "terceira": "airport/TER",
  "teresina": "airport/THE",
  "termez": "airport/TMZ",
  "terrace": "airport/YXT",
  "terre haute": "airport/HUF",
  "texarkana": "airport/TXK",
  "thaba'nchu": "airport/TCU",
  "the pas": "airport/YQD",
  "thessaloniki": "airport/SKG",
  "thief river falls": "airport/TVF",
  "thira": "airport/JTR",
  "thiruvananthapuram": "airport/TRV",
  "thisted": "airport/TED",
  "thompson": "airport/YTH",
  "thorne bay": "airport/KTB",
  "thunder bay": "airport/YQT",
  "thursday island": "airport/TIS",
  "tianjin": "airport/TSN",
  "tijuana": "airport/TIJ",
  "tioman": "airport/TOD",
  "tirana": "airport/TIA",
  "tiruchirapally": "airport/TRZ",
  "tivat": "airport/TIV",
  "tobago": "airport/TAB",
  "tokushima": "airport/TKS",
  "tokyo": "airport/TYO",
  "toledo": "airport/TOL",
  "tom price": "airport/TPR",
  "toowoomba": "airport/TWB",
  "toronto": "airport/YTO",
  "tortola": "airport/TOV",
  "touho": "airport/TOU",
  "toulouse": "airport/TLS",
  "townsville": "airport/TSV",
  "toyama": "airport/TOY",
  "trabzon": "airport/TZX",
  "trapani": "airport/TPS",
  "traverse city": "airport/TVC",
  "treasure cay": "airport/TCB",
  "trenton/princeton": "airport/TTN",
  "treviso": "airport/TSF",
  "tri": "airport/TRI",
  "trieste": "airport/TRS",
  "tripoli": "airport/TIP",
  "tromsoe": "airport/TOS",
  "trondheim": "airport/TRD",
  "tsumeb": "airport/TSB",
  "tucson": "airport/TUS",
  "tulepo": "airport/TUP",
  "tulsa": "airport/TUL",
  "tunis": "airport/TUN",
  "turbat": "airport/TUK",
  "turin": "airport/TRN",
  "turku": "airport/TKU",
  "tuscaloosa": "airport/TCL",
  "tuxtla gutierrez": "airport/TGZ",
  "twin falls": "airport/TWF",
  "tyler": "airport/TYR",
  "ua huka": "airport/UAH",
  "ua pou": "airport/UAP",
  "ube": "airport/UBJ",
  "uberaba": "airport/UBA",
  "uberlandia": "airport/UDI",
  "ubon ratchathani": "airport/UBP",
  "udaipur": "airport/UDR",
  "uden": "airport/UDE",
  "udon thani": "airport/UTH",
  "ufa": "airport/UFA",
  "uherske hradiste": "airport/UHE",
  "uige": "airport/UGO",
  "ujung pandang": "airport/UPG",
  "ukhta": "airport/UCT",
  "ukiah": "airport/UKI",
  "ulaanbaatar": "airport/ULN",
  "ulan": "airport/UUD",
  "ulanhot": "airport/HLH",
  "ulei": "airport/ULB",
  "ulsan": "airport/USN",
  "ulundi": "airport/ULD",
  "umea": "airport/UME",
  "umiujaq": "airport/YUD",
  "umtata": "airport/UTT",
  "unalakleet": "airport/UNK",
  "union island": "airport/UNI",
  "unst": "airport/UNT",
  "upala": "airport/UPL",
  "upernavik": "airport/JUV",
  "upington": "airport/UTN",
  "upolu point": "airport/UPP",
  "uranium city": "airport/YBE",
  "urgench": "airport/UGC",
  "uriman": "airport/URM",
  "urmiehm": "airport/OMH",
  "uruapan": "airport/UPN",
  "urubupunga": "airport/URB",
  "uruguaiana": "airport/URG",
  "urumqi": "airport/URC",
  "uruzgan": "airport/URZ",
  "ushuaia": "airport/USH",
  "utapao": "airport/UTP",
  "utica": "airport/UCA",
  "utila": "airport/UII",
  "uummannaq": "airport/UMD",
  "uzhgorod": "airport/UDJ",
  "vaasa": "airport/VAA",
  "vaexjoe": "airport/VXO",
  "vail": "airport/EGE",
  "val d'or": "airport/YVO",
  "valdez": "airport/VDZ",
  "valdosta": "airport/VLD",
  "valencia": "airport/VLC",
  "valladolid": "airport/VLL",
  "valparaiso": "airport/VAP",
  "valverde": "airport/VDE",
  "van": "airport/VAN",
  "vancouver": "airport/YVR",
  "varadero": "airport/VRA",
  "varanasi": "airport/VNS",
  "varkaus": "airport/VRK",
  "varna": "airport/VAR",
  "vasteras": "airport/VST",
  "velikiye luki": "airport/VLU",
  "venice": "airport/VCE",
  "veracruz": "airport/VER",
  "vernal": "airport/VEL",
  "vero beach/ft. pierce": "airport/VRB",
  "verona": "airport/VRN",
  "victoria": "airport/YYJ",
  "victoria falls": "airport/VFA",
  "vidin": "airport/VID",
  "vientiane": "airport/VTE",
  "vigo": "airport/VGO",
  "villahermosa": "airport/VSA",
  "vilnius": "airport/VNO",
  "virgin gorda": "airport/VIJ",
  "visalia": "airport/VIS",
  "visby": "airport/VBY",
  "vitoria": "airport/VIT",
  "vitoria": "airport/VIX",
  "vryheid": "airport/VYD",
  "wabush": "airport/YWK",
  "waco": "airport/ACT",
  "wagga": "airport/WGA",
  "walla walla": "airport/ALW",
  "wallis": "airport/WLS",
  "walvis bay": "airport/WVB",
  "warrnambool": "airport/WMB",
  "warsaw": "airport/WAW",
  "washington dc": "airport/IAD",
  "waterloo ia": "airport/ALO",
  "watertown": "airport/ATY",
  "wausau/stevens point": "airport/CWA",
  "weipa": "airport/WEI",
  "welkom": "airport/WEL",
  "wellington": "airport/WLG",
  "wenatchee": "airport/EAT",
  "west palm beach": "airport/PBI",
  "west yellowstone": "airport/WYS",
  "westerland": "airport/GWT",
  "whakatane": "airport/WHK",
  "whale cove": "airport/YXN",
  "whangarei": "airport/WRE",
  "white plains": "airport/HPN",
  "whitehorse": "airport/YXY",
  "whitsunday resort": "airport/HAP",
  "whyalla": "airport/WYA",
  "wichita": "airport/ICT",
  "wichita falls": "airport/SPS",
  "wick": "airport/WIC",
  "wickham": "airport/WHM",
  "wien": "airport/VIE",
  "wiesbaden": "airport/WIE",
  "wilkes barre/scranton": "airport/AVP",
  "williamsport": "airport/IPT",
  "williston": "airport/ISL",
  "wilmington": "airport/ILM",
  "wilna": "airport/VNO",
  "wiluna": "airport/WUN",
  "windhoek": "airport/WDH",
  "windhoek": "airport/ERS",
  "windsor ontario": "airport/YQG",
  "winnipeg international": "airport/YWG",
  "wolf point": "airport/OLF",
  "wollongong": "airport/WOL",
  "woomera": "airport/UMR",
  "worcester": "airport/ORH",
  "worland": "airport/WRL",
  "wrangell": "airport/WRG",
  "wuhan": "airport/WUH",
  "wyndham": "airport/WYN",
  "xiamen": "airport/XMN",
  "xi'an": "airport/XIY",
  "yakima": "airport/YKM",
  "yakutat": "airport/YAK",
  "yakutsk": "airport/YKS",
  "yamagata": "airport/GAJ",
  "yamoussoukro": "airport/ASK",
  "yanbu": "airport/YNB",
  "yangon": "airport/RGN",
  "yaounde": "airport/YAO",
  "yellowknife": "airport/YZF",
  "yichang": "airport/YIH",
  "yokohama": "airport/YOK",
  "yuma": "airport/YUM",
  "zacatecas": "airport/ZCL",
  "zadar": "airport/ZAD",
  "zagreb": "airport/ZAG",
  "zakynthos": "airport/ZTH",
  "zaragoza": "airport/ZAZ",
  "zhob": "airport/PZH",
  "zinder": "airport/ZND",
  "zouerate": "airport/OUZ",
  "zurich": "airport/ZRH"
}


//find airport code by city name
var iata = {
  getCode: function(location) {
    if (dest[location.toLowerCase()] !== undefined) {
      return(dest[location.toLowerCase()]);
    } else{
      return("")  //N/A
    }
  }
};

module.exports = iata;
